### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by fabaff** [kparal/jabber-roster#2]
Are there any plan for Python3 support?

jabber-roster is available as RPM from the Fedora Package Collection and with the on-going effort of Fedora to move to Python 3 it would be nice to keep jabber-roster [1]. There is no hurry because some of jabber-rosters dependencies are still lacking Python 3 support.

[1] http://portingdb-encukou.rhcloud.com/pkg/jabber-roster/

**Comment by kparal** [comment]
If the deps are ported, why not. This is a 100 lines of code, should be doable :)

**Comment by kparal** [comment]
I don't develop this anymore.
